#!/usr/bin/expect -f

#spawn AutoGit

spawn git push

set username [lindex $argv 0];
set password [lindex $argv 1];

spawn echo $username
spawn echo $password

expect "*sername for*"
send -- "$username\r"
expect "*assword for*"
send -- "$password\r"

exit
