#!/usr/bin/expect -f

set username [lindex $argv 0];
set password [lindex $argv 1];

echo username
echo password

expect "*sername for*"
send -- "$username\r"
expect "*assword for*"
send -- "$password\r"
