#!/usr/bin/expect -f

spawn AutoGit

set username [lindex $argv 0];
set password [lindex $argv 1];

send "echo username"
echo password

expect "*sername for*"
send -- "$username\r"
expect "*assword for*"
send -- "$password\r"
