#!/bin/bash -f
set timeout -1

#script for updating the index.html file of the pages site with new ip
ipaddr=$1
username=$2
password=$3

echo "<h>$ipaddr</h>" > index.html


git add .
git commit -m "auto-updated ip"
git push

./AutoGit -$2 -$3
